export type TagVariant =
  | "three"
  | "websockets"
  | "react"
  | "redis"
  | "gray"
  | "html"
  | "css"
  | "javascript"
  | "node"
  | "next"
  | "kubernetes"
  | "postgresql"
  | "ogl"
  | "glsl"
  | "angular"
  | "ionic"
  | "uxui"
  | "a11y"
  | "seo"
  | "analytics"
  | "drupal"
  | "ecommerce"
  | "automation"
  | "ai"
  | "wordpress"
  | "woocommerce"
  | "branding"
  | "responsive"
  | "animation";

export const tagLabels = {
  three: "Three.js",
  websockets: "WebSockets",
  react: "React",
  redis: "Redis",
  gray: "Gray",
  html: "HTML",
  css: "CSS",
  javascript: "JavaScript",
  node: "Node.js",
  next: "Next.js",
  kubernetes: "Kubernetes",
  postgresql: "PostgreSQL",
  ogl: "OGL.js",
  glsl: "GLSL",
  angular: "Angular",
  ionic: "Ionic",
  uxui: "UX/UI",
  a11y: "A11y",
  seo: "SEO",
  analytics: "Analytics",
  drupal: "Drupal",
  ecommerce: "eCommerce",
  automation: "Automatizacion",
  ai: "IA",
  wordpress: "WordPress",
  woocommerce: "WooCommerce",
  branding: "Branding",
  responsive: "Responsive",
  animation: "Animacion",
} as const satisfies Record<TagVariant, string>;
